### PR TITLE
Suppress exception in case of empty curl response

### LINKED ISSUE #78: Empty response now triggers json exception (1.4.4)
We've discovered a critical breakage in our behat CI caused by the recent 1.4.4 release.

I've traced this to https://github.com/instaclick/php-webdriver/pull/67.

An example broken build can be seen at https://travis-ci.org/silverstripe/silverstripe-framework/jobs/248559035

Our selenium server log shows the requests being passed through to it without any apparent error.

```10:32:35.986 INFO - Executing: [set window size] at URL: /session/96d209e0-a12b-43ae-aa50-eff91550202d/window/current/size)
10:32:36.017 INFO - Done: /session/96d209e0-a12b-43ae-aa50-eff91550202d/window/current/size
```

The issue is caused in AbstractWebDriver when `$rawResult` is empty. It looks as though selenium emits an empty body for this request. Previously in 1.4.3 this would incorrectly attempt to parse this as json, but fail silently.

In 1.4.4 this will incorrectly attempt to parse this as json, but raise an error.

What should probably happen is that empty results aren't parsed at all, but left empty.

We are using selenium 2.41.0.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #78

### CODE REVIEW

**Comment by tractorcow** [comment]
@robocoder if this build is successful, do you think you could please push out a 1.4.5?

**Comment by robocoder** [comment]
Reviewing now...

File: lib/WebDriver/ServiceFactory.php [hunk 1]
```diff
@@ -103,6 +103,11 @@ public function setServiceClass($serviceName, $className)
             $className = '\\' . $className;
         }
 
+        // Flush outdated service cache
+        if (isset($this->serviceClasses[$serviceName]) && $this->serviceClasses[$serviceName] !== $className) {
+            unset($this->services[$serviceName]);
```
Comment (robocoder) [inline lib/WebDriver/ServiceFactory.php]: What version of php requires this? Looks like a refcount hack.

File: test/Test/WebDriver/WebDriverTest.php [hunk 2]
```diff
@@ -221,4 +225,22 @@ public function testSeleniumNoResponse()
 
         $this->assertEquals(null, $out);
     }
+
+    /**
+     * Assert that empty response does not trigger exception, but invalid JSON does
+     */
+    public function testNonJsonResponse()
+    {
+        ServiceFactory::getInstance()->setServiceClass('service.curl', '\\Test\\WebDriver\\TestCurlService');
```
Comment (robocoder) [inline test/Test/WebDriver/WebDriverTest.php]: I strongly feel this should be served by a mock.

File: lib/WebDriver/AbstractWebDriver.php [hunk 3]
```diff
@@ -128,38 +128,44 @@ protected function curl($requestMethod, $command, $parameters = null, $extraOpti
...
-        $result = json_decode($rawResult, true);
+        $result = [];
+        $value = null;
+        if (!empty($rawResult)) {
+            $result = json_decode($rawResult, true);
 
-        if ($result === null && json_last_error() != JSON_ERROR_NONE) {
-            throw WebDriverException::factory(WebDriverException::CURL_EXEC, 'Payload received from webdriver is not valid json: ' . substr($rawResult, 0, 1000));
-        }
+            if ($result === null && json_last_error() != JSON_ERROR_NONE) {
```
Comment (robocoder) [inline lib/WebDriver/AbstractWebDriver.php]: I'm going to rewrite this since we want to push a fix tonight while maintaining our coding standards (eg no nested if).

Comment (tractorcow) [inline lib/WebDriver/AbstractWebDriver.php]: Oh, I apologise for the mis-standard! Your standard is a good one. :)

File: test/Test/WebDriver/WebDriverTest.php (hunk 2 above)
Comment (tractorcow) [inline test/Test/WebDriver/WebDriverTest.php]: Yes also, but I was hesitant to make any strong changes to an unrelated API. ServiceFactory would be good if you could inject a mock directly.

File: lib/WebDriver/ServiceFactory.php (hunk 1 above)
Comment (tractorcow) [inline lib/WebDriver/ServiceFactory.php]: It's not PHP version specific; ServiceFactory::getService() would ignore any updated serviceClass if an outdated service exists for any prior value. This is necessary to force the `new $className` to trigger in any subsequent getService() call.

I would replace with setService() to allow a mock to be directly injected.

Comment (robocoder) [inline lib/WebDriver/ServiceFactory.php]: Sorry, I understand what's going on now. I was skimming the code from my phone earlier.
